# Generated by Django 3.1.2 on 2020-10-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201023_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='delivered',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
