# Generated by Django 3.1.2 on 2020-10-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_shipping_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
