# Generated by Django 3.1.2 on 2020-11-05 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20201105_1758'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SlideProducts',
            new_name='SlideProduct',
        ),
    ]
