# Generated by Django 3.1.2 on 2020-11-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20201105_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('N', 'New'), ('D', 'Discounts'), ('BS', 'Best-Sellers')], max_length=2, null=True),
        ),
    ]
